### ISSUE TITLE
Not working anymore?

### ISSUE THREAD

**Issue by appcoders** [marcoscheel/M365.TeamsBackup#1]
Hi @marcoscheel,

I tried your tool today, but I am getting an error on connection:

```
M365.TeamsBackup.Core.Services.BackupFromGraphService[0]
      Team read page error: https://graph.microsoft.com:443/beta/me/joinedTeams
      Status Code: Forbidden
      Microsoft.Graph.ServiceException: Code: Forbidden
      Message: Missing scope permissions on the request. API requires one of 'Team.ReadBasic.All, TeamSettings.Read.All, TeamSettings.ReadWrite.All, User.Read.All, Directory.Read.All, User.ReadWrite.All, Directory.ReadWrite.All'. Scopes on the request 'User.Read, 
profile, openid, email'


```

If I change the scope in Preferences to the listen permissions I get:
`
      AADSTS650053: The application 'Graph API Device Code' asked for scope 'Team.ReadBasic.All,' that doesn't exist on the resource '00000003-0000-0000-c000-000000000000'. Contact the app vendor.`

Where I am going wrong?
Thanks.

**Comment by marcoscheel** [comment]
Hi,
Thanks for reaching out. Did you setup the application and granted the permissions:
https://github.com/marcoscheel/M365.TeamsBackup/blob/main/deploy/create-aadapp.ps1

It looks like you are missing the grant for the application.

This is my blog post regarding the setup of the app:
https://marcoscheel.de/post/2021/01/20210124-m365teamsbackup-aadapp/

Ciao Marco

**Comment by appcoders** [comment]
Thanks a lot - I oversee this - my fault :-)
